apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: {{ .Values.namespace }}
data:
  db.sql: |
    GRANT ALL PRIVILEGES ON DATABASE student_crud_api TO app_user;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
          - name: POSTGRES_PASSWORD
            value: "app_pass123"
          - name: POSTGRES_USER
            value: "app_user"
          - name: POSTGRES_DB
            value: "student_crud_api"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-init-vol
            mountPath: /docker-entrypoint-initdb.d/db.sql
            subPath: db.sql
      volumes:
        - name: postgres-init-vol
          configMap:
            name: postgres-init-script
            items:
              - key: db.sql
                path: db.sql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
