version: '3'

services:
  student_crud_api:
    image: akshay754/student_crud_api:latest
    environment:
      DB_USERNAME: app_user
      DB_PASSWORD: app_pass123
      DB_HOST: postgres
    ports:
      - "5000:5000"
    networks:
      - appnet
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=app_pass123
      - POSTGRES_USER=app_user
      - POSTGRES_DB=student_crud_api
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - appnet

networks:
  appnet:
    driver: bridge