replica_count: 2
name: student-crud-api
namespace: master
image:
  repository: akshay754/student_crud_api
  tag: 49c3a24aaa8308c31be85c5f753cdaadeed70800
containerPort: 5000

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000