replica_count: 2
name: student-crud-api
namespace: master
image:
  repository: akshay754/student_crud_api
  tag: 3d77c6dab1d6b187d746282ab5d925af4a4d1e3a
containerPort: 5000

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000