replica_count: 2
name: student-crud-api
namespace: master
image:
  repository: akshay754/student_crud_api
  tag: 4247079064c73b71f4589a7ddfb2c5760ff48da5
containerPort: 5000

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000