replica_count: 2
name: student-crud-api
namespace: master
image:
  repository: akshay754/student_crud_api
  tag: eeb8204afc6186480038ceb8075566d5874b1431
containerPort: 5000

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000