apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: student-crud-api-preview-env
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: akshay-sri123
          repo: student-crud-api
          tokenRef:
            secretName: github-secret
            key: token
          labels:
            - preview
        requeueAfterSeconds: 15
  template:
    metadata:
      name: "{{branch}}-{{number}}-preview-env"
    spec:
      source:
        path: helm/student-crud-api
        repoURL: https://github.com/akshay-sri123/student-crud-api
        targetRevision: "{{head_sha}}"
        helm:
          parameters:
            - name: "image.tag"
              value: "{{head_short_sha_7}}"
            - name: "namespace"
              value: "{{branch}}-{{number}}-preview-env"
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      destination:
        namespace: "{{branch}}-{{number}}-preview-env"
        server: https://kubernetes.default.svc
