name: CI
run-name: Application Pipeline
on: [push]
env:
  DOCKER_HUB_USERNAME: akshay754
  DOCKER_HUB_PASSWORD: ZG9ja2VyMTEyMzU4MTM=
  DOCKER_HUB_REPOSITORY: akshay754/student_crud_api
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          make requirements
          make lint

      - name: Build docker image
        run: |
          make docker_build

      - name: Push the docker image
        run: |
          make docker_push

  CD:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/preview-environments'
    needs: CI
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update helm charts
        run: |
          git_hash=$(git rev-parse "$GITHUB_SHA")
          version=$(cat ./helm/student-crud-api/values.yaml | grep tag: | awk '{print $2}')
          sed -i "s/$version/$git_hash/" ./helm/student-crud-api/values.yaml

      - name: Commit changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Updated version

  #     - name: Deploy onto Vagrant
  #       env:
  #         VAGRANT_SSH_KEY: ${{ secrets.VAGRANT_SSH_KEY }}
  #       shell: bash
  #       run: |
  #         echo "$VAGRANT_SSH_KEY" | tr -d '\r' > id_rsa
  #         chmod 0400 id_rsa
  #         ssh-add id_rsa
  #         scp -i id_rsa -P 2222 docker-compose.yaml vagrant@127.0.0.1:/home/vagrant
  #         scp -i id_rsa -P 2222 init.sql vagrant@127.0.0.1:/home/vagrant
  #         ssh -i id_rsa -p 2222 vagrant@127.0.0.1 "sudo docker compose up"
