name: CI
run-name: ${{ github.actor }} is running CI 🚀
on: [push]
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          make requirements
          make lint

      - name: Build docker image
        run: |
          make docker_build

  CD:
    runs-on: self-hosted
    steps:
      - name: Deploy on local
        run: |
          make app_run_docker_compose